# This is a basic workflow to help you get started with Actions

name: RELEASE

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
    
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow builds the Java app!
  # This workflow submites the release
  release:
    if: startsWith(github.event.head_commit.message, '[release]') == true
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    # Can build any Java version
    strategy:
      matrix:
        java: [ '11' ]
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Code Checkout
      - name: Code Checkout
        uses: actions/checkout@v3
      # Runs as Java
      - name: Set up JDK ${{ matrix.java }}
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: ${{ matrix.java }}
      # Print env
      - name: Print env
        run: env
      # Print settings xml
      - name: Print settings.xml
        run: cat ~/.m2/settings.xml
      # Runs a set of commands using the runners shell
      - name: Publish package
        run: ./mvnw --batch-mode deploy
        env:
          GITHUB_TOKEN: ${{ github.token }} # GITHUB_TOKEN is the default env for the password